M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu20.04.1} date Wed 05 Jul 2023 09:04:26 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-05T21:04:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.1626Y-2.8291
X5.1626Y-3.0567
T0
M30
