M48
; DRILL file {KiCad 7.0.5-7.0.5~ubuntu22.04.1} date Tue 06 Jun 2023 03:21:45 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-06T15:21:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-7.0.5~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.1626Y-2.8291
X5.1626Y-3.0567
T0
M30
